name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - uses: php-actions/composer@v6
      
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: "9.6"
          bootstrap: vendor/autoload.php
          args: --coverage-text
          php_version: "8.1"
